name: "Docker Actions"

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: "hello-github-action"
        run: |
          echo Hello, world!