name: "Docker Actions - Joke"

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Random joke
        uses: ./.github/actions/random-joke

