# https://github.com/marketplace/actions/slack-send
name: Pull Request Workflow

on: 
  pull_request:
    branches: [main-practice]

jobs:
  action:
    runs-on: ubuntu-latest
    name: New PR to repo
    steps:
      - uses: actions/checkout@v1
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: D02AGBETYQY
          slack-message: New Pull Request to main-practice branch
        env:
          SLACK_WEBHOOK_URL: $ {{ secrets.SLACK_WEBHOOK_URL }}
      